### ISSUE TITLE
Cannot read property 'renderer' of undefined

### ISSUE THREAD

**Issue by xhlulu** [plotly/dash-vtk#2]
In bee113777415ec6c399808e6c0b25c2a4d4724f7, we are faced with an error "Cannot read property 'renderer' of undefined":

It seems like the cause of the problem resides here:
https://github.com/plotly/dash-vtk/blob/bee113777415ec6c399808e6c0b25c2a4d4724f7/src/lib/components/VtkGeometryRepresentation.react.js#L44-L64

**Comment by jourdain** [comment]
That is because the `view` property is not passed by the parent when it is cloning and adding a ref to itself.

Run `npm start` to see the code works without dash.

**Comment by jourdain** [comment]
In my last commit, I'm preventing any error with debug output. 
In the the log, you can clearly see the `view` property added but still not available in the child react element.

**Comment by jourdain** [comment]
Basically the main issue is that [line](https://github.com/plotly/dash-vtk/blob/main/src/lib/components/VtkView.react.js#L57) does not seems to be properly handled within dash context.

**Comment by xhlulu** [comment]
This indeed seems pretty weird. I'm not familiar with how `React.Children.map` and `React.cloneElement` behave and I've never used them when wrapping dash components.  I don't know how Dash renders react behind the scene, I think @alexcjohnson @Marc-Andre-Rivet might have a better idea why we might be getting `undefined` instead of the correct prop value.
