### ISSUE TITLE
Make dash_vtk.View accept a style argument

### ISSUE THREAD

**Issue by xhlulu** [plotly/dash-vtk#26]
I like to set the height of `dash_vtk.View` to `"100%"`, but to do this I need to update the style of the container like this:
```python
view = html.Div(
    dash_vtk.View(...),
    style={'height': '100%'}
)
```

I feel it would be simpler if I could edit the style of the view component directly to accomplish the same thing:
```python
view = dash_vtk.View(..., style={'height': '100%'})
```

I also think having a default `height` and/or `min-height` argument would be nice so it wouldn't confuse people that don't see anything displayed.

**Comment by jourdain** [comment]
The View take the size of its parent container. A div by default does not have any height. Hence the problem. The other issue, is that the View should allow its container to shrink.

Right now, the style of the view is `{ width: '100%', height: '100%', position: 'relative' };`

**Comment by jourdain** [comment]
I agree on the min-height, but that won't still solve your problem...

**Comment by xhlulu** [comment]
> The View take the size of its parent container. 

I think being able to directly edit the style would still be nice since we wouldn't need to add a unnecessary parent wrapper.

> I agree on the min-height, but that won't still solve your problem... What value do you want for min-height?

What does vtk.js use by default? I think 300px sounds good but if you think there's a better choice please go ahead with that :)

**Comment by jourdain** [comment]
300px as min might be too big. VTK use 300x300 by default, but you can still can shrink it if you set it. If we set min-height/width to 300px, you won't be able to go lower. I'm think 100x100 would guaranty the user to see something and he will know that something is up...

I'll add the possibility to override the style from outside. But in any case that won't solve the problem as the View is already set with a height and width of 100%.

**Comment by xhlulu** [comment]
This is the console output:

![image](https://user-images.githubusercontent.com/21180505/108269587-3371bb00-713c-11eb-874f-12aeb64b9dc9.png)

**Comment by jourdain** [comment]
You can provide either `style` or `className` and those will be passed down to the root component of the view.

```
commit 1ce8567205cbd36b4d9a076f9f293b47efef120e (HEAD -> master, origin/master)
Author: Sebastien Jourdain <sebastien.jourdain@kitware.com>
Date:   Thu Feb 18 14:51:46 2021 -0700

    chore(build): Add generated files

commit db621fe49957a687f5b4f4702c02dfeabbd91dcc
Author: Sebastien Jourdain <sebastien.jourdain@kitware.com>
Date:   Thu Feb 18 14:50:55 2021 -0700

    doc(View): Update props to include style/className
```

**Comment by xhlulu** [comment]
Amazing, thanks!
