### ISSUE TITLE
How to set colorWindow and colorLevel

### ISSUE THREAD

**Issue by xhlulu** [plotly/dash-vtk#30]
I'm reading the explanation for colorWindow and colorLevel:
```
colorWindow

Controls the window in a window level mapping of the input image. Window
level mapping is a technique to map the raw data values of an image
into screen intensities in a manner akin to

pixelIntensity = (inputValue - level)/window;
colorLevel

Controls the level in a window level mapping of the input image. Window
level mapping is a technique to map the raw data values of an image
into screen intensities in a manner akin to

pixelIntensity = (inputValue - level)/window;
```

From this I realize that it's a shift & rescaling of the original value so that they are in a range accepted by the slice component. However it's not really clear how I'm supposed to set the level and window; do we want to rescale them in a range 0-255, 0-1, or something else? I'm looking at the source code for [this script](https://github.com/plotly/dash-vtk/blob/master/docs/tutorials/s04_slice.py), but I'm not sure how 500 and 200 make sense here; we would get:
```
pixelIntensity = (x - 200) / 500
```

but since x is a value in range (0, 1), we'd be getting a value between -2/5 and -1.99/5?

**Comment by jourdain** [comment]
Window = (max - min)
Level = (max + min) * 0.5

**Comment by xhlulu** [comment]
Amazing! I didn't realize it wasn't `random.random()` but rather `random.random() * i`; my bad!

The solution works very well.
