### ISSUE TITLE
Add binary transport

### ISSUE THREAD

**Issue by xhlulu** [plotly/dash-vtk#42]
Binary transport will potentially lower the size of the arrays being passed to JS, and might speed up the process as well.

**How we could implement it:** Given a numpy array, we compute the shape, the dtype, the b64 encoded memory view of the flattened numpy array. Then those three values are passed as a dict/json to the frontend, which is then reconstructed into a typedarray. The plan would be to use this [function on the python side](https://github.com/plotly/plotly.py/pull/2943/files#diff-b4b889b2e16cacd607e69667213866ef517f16b84ed9154de194fa849ec45f63R235).

For more information, see [this pull request](https://github.com/plotly/plotly.js/pull/5230/files#diff-8312907943a9173f911eef0ac2e1993f8b23de01e44ea9429d16d3a4fd9a5f73R32) as well as https://github.com/plotly/plotly.py/pull/2943

**Comment by jourdain** [comment]
Done in https://github.com/plotly/dash-vtk/pull/43
