### ISSUE TITLE
dcc.Loading() and dash_vtk.View()

### ISSUE THREAD

**Issue by J3ffx** [plotly/dash-vtk#46]
Hello,

I'd like to use the `dcc.Loading()` and put a `dash_vtk.View()` inside in order to display the loading icon when dash_vtk is building the view. But it looks like the view is disabled when inside the `dcc.Loading` component.

Without the loading component : 
`dash_vtk.View(id="vtk-view")`
![image](https://user-images.githubusercontent.com/48691129/115261645-148ba700-a134-11eb-9f62-0ab7e84523c4.png)

Without the loading component : 
`dcc.Loading(dash_vtk.View(id="vtk-view"))`
![image](https://user-images.githubusercontent.com/48691129/115261914-5583bb80-a134-11eb-86e7-fc4ca06aad2b.png)

So the questions are : Is it a functionnality to come or is it supposed to work at the moment ? And if there is another way to do it, how can we add a loading state to a dash_vtk View ?

**Comment by xhlulu** [comment]
You need to manually set a width and a height: https://github.com/plotly/dash-sample-apps/blob/16e6bd827cb3b9a60e35ef0214a3557e6fa7a63e/apps/dash-vehicle-geometry/app.py#L175-L187

**Comment by J3ffx** [comment]
Okay, I see, you solved it with the example ! I was trying to put the loading just on the view but i had to put it on the component containing the view. Thanks a lot !
