### ISSUE TITLE
Color legend

### ISSUE THREAD

**Issue by francolovato** [plotly/dash-vtk#52]
Hello everyone!

I'm building a web app using dash_vtk in python to visualize CFD data, so for now 3D surfaces coloured based on some parameter value like pressure. So far everything's good, but can't activate the colour legend and I saw no example with it, so I'm starting to question if it is possible at this point. To be clear, I'd like to be able to associate a value to the colours I'm seeing. I saw the example with the F1 car where values are displayed when hovering, but I'd prefer a simple scale. Is it possible?

Thank you,
Franco

**Comment by jourdain** [comment]
You should be able to provide [those options](https://github.com/Kitware/react-vtk-js/blob/master/src/core/GeometryRepresentation.js#L279-L293)

**Comment by francolovato** [comment]
Thank you jourdain, I tried providing "showScalarBar= True" inside the dash_vtk.GeometryRepresentation but it gives an error saying that this component only accepts the following arguments: actor, children, colorDataRange, colorMapPreset, cubeAxesStyle, id, mapper, property, showCubeAxes.
I'm using dash_vtk 0.0.9 on dash 1.20, is it too old?

**Comment by jourdain** [comment]
Actually, looking at the code. The JS version in dash-vtk support it. It is just dash-vtk that it not exposing it.

**Comment by francolovato** [comment]
Ok, is there something I can do from my side or should I wait for an update?

**Comment by xhlulu** [comment]
@francolovato if you want to use it asap you can modify the source code of the geometryrepresentation component by adding the new prop inside proptypes. The code should be in src/lib/components

Once it's modified you can run npm run build to generate the new js bundle, and you should be able to use it.

**Comment by francolovato** [comment]
Thank you @xhlulu I'll give it a try!

**Comment by francolovato** [comment]
@xhlulu I followed your instructions and it's working fine, thank you very much!!

**Comment by francolovato** [comment]
@xhlulu I followed your instructions and it's working fine, thank you very much!!

**Comment by zhenhuiii** [comment]
Hi, was just wondering if showScalarBar is still unexposed in the dash_vtk python library?
