### ISSUE TITLE
Loading mesh in

### ISSUE THREAD

**Issue by dodointhesnow** [plotly/dash-vtk#54]
I am trying to load a mesh/multiple meshes I created with vedo which is based off vtk. Upon loading into the dash I get a type error for Mesh is not JSON serializable. Any suggestions on how to fix?

Thanks

**Comment by jourdain** [comment]
Did you use the mesh helper? 

https://github.com/plotly/dash-vtk/blob/master/demos/usage-vtk-cfd/app.py#L83

**Comment by dodointhesnow** [comment]
I didn’t because I thought the mesh was already in a mesh state. What data type does the to_mesh_state take in and does it preserve colors?

**Comment by jourdain** [comment]
Any vtkDataSet, you just need to list which fields you want to keep for the client.

**Comment by dodointhesnow** [comment]
Gotcha, so I’d have to convert the vedo mesh into a vtk format then proceed similar to the example?

**Comment by jourdain** [comment]
I would guess so

**Comment by dodointhesnow** [comment]
Ok thank you I’ll see what I can come up with and if I come up with a solution will post here for others in the future.

**Comment by dodointhesnow** [comment]
> I would guess so

I was able to use the converter when using a vedo mesh and the ._data term. However I lose all coloring that was on the original mesh when doing this and couldn’t get the the mapper for the color to load in either. Do you have any examples of a predetermined color map determined by interpolation loaded into dash?

**Comment by jourdain** [comment]
The line I shared before does that with only 1 field. But you can provide a [full list of strings for points and cells](https://github.com/plotly/dash-vtk/blob/master/dash_vtk/utils/vtk.py#L74).

You also have that [example](https://github.com/plotly/dash-sample-apps/blob/main/apps/dash-vehicle-geometry/app.py#L63).

**Comment by dodointhesnow** [comment]
Hm ok. I’m trying to figure out how I’d specify to keep the colors in the field_to_keep. I’m not sure what name to pass so the polydata.GetPointData().GetArray(name) will retrieve the color map. Not sure if you have experience since it’s a vedo mesh

**Comment by dodointhesnow** [comment]
I have a field named PointScalars which I’m inputting but it just shows an error for the dash itself

**Comment by jourdain** [comment]
The color map is independent from the field on your mesh. Unless it is actually a RGB(A) field. The color maps is something that convert a float/double into a given color. 

What is the error and what are you doing? So far dash-vtk allow you to move a mesh with data to the client for local rendering. After how things get configured in term of rendering is up to the user to tune that part using the mapper properties.

**Comment by dodointhesnow** [comment]
So I’m using the to_mesh_state function and using the field_to_keep=‘PointScalars’ and the error is:Object of type vtkOpenGLActor is not Json serializable. 

Sorry if I’m missing something pretty bee to dash vtk

**Comment by jourdain** [comment]
It seems that your mesh is not a vtkDataSet but a vtkActor.  Unless that error is coming from somewhere else. Maybe you are trying to pass that actor as an arg somewhere?

If what you have is an actor rather than a mesh, you might be able to get the mesh from it by doing something along that line
`dataset = actor.GetMapper().GetInput()`

**Comment by dodointhesnow** [comment]
I was able to get the poly data using surface._data which loads fine but doesn’t contain the color. Once I add the field to keep it errors and gives that error message.
Thanks again for your help

**Comment by jourdain** [comment]
I don't understand how the vtkActor serialization error happen.

Are you calling `to_mesh_state(surface._data, field_to_keep="PointScalars")`

And if you don't pass that second arg, you don't have any error?

**Comment by dodointhesnow** [comment]
Correct it runs smooth (minus the color) without the second arg. I checked to make sure that field is present which it is in the PointData

**Comment by jourdain** [comment]
How do you build your `dash_vtk.View` hierarchy? The actor must come from here. I'm just not sure why without seeing your piece of code.
