### ISSUE TITLE
Is 'dash-vtk' missing?

### ISSUE THREAD

**Issue by lihuaiguang** [plotly/dash-vtk#57]
Hi, Sebastian, I have the errors of missing dash-vtk. How to solve it? Thank you.

% npm install dash-vtk
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/dash-vtk - Not found
npm ERR! 404 
npm ERR! 404  'dash-vtk@*' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by jourdain** [comment]
dash-vtk is not published on npm, it is a python package available on PyPI. But if you want, you can use [react-vtk-js](https://github.com/Kitware/react-vtk-js) which is on npm.

**Comment by lihuaiguang** [comment]
Thank you.
