### ISSUE TITLE
New pypi release

### ISSUE THREAD

**Issue by HansKallekleiv** [plotly/dash-vtk#67]
Hi, would it be possible to get a new release on Pypi with the colorscale and orientationaxis?

**Comment by xhlulu** [comment]
You can install the latest version of a repo with:

```
pip install git+https://github.com/plotly/dash-vtk
```

**Comment by HansKallekleiv** [comment]
Thanks @xhlulu.
Yes we could install from git, but currently the generated python classes are not updated in the repo so it will still be an older version.

**Comment by xhlulu** [comment]
Oh that's true. Well in the meantime (before the maintainers create a new release) you can build a custom release following those instructions: https://github.com/plotly/dash-vtk/blob/master/docs/CONTRIBUTING.md#publishing

**Comment by HansKallekleiv** [comment]
Yes, you are right. That is what I'm doing now, and it works fine :) 
It is not critical to get a new release, but we are doing extensive testing of VTK/VTK.js with Dash at the moment, and part of that testing is to deploy some dash apps to Azure. Currently our deploy pipeline does not include npm, so it is a bit of a hazzle getting it running.

**Comment by xhlulu** [comment]
Not sure if it helps, but you might be able to commit the `tar.gz` that's created from `python setup.py sdist` along with your file, and use a local file install like `pip install dash_vtk.tar.gz` or something like this.

**Comment by tbridel** [comment]
Good afternoon @xhluca  !

Any news regarding the next release ?

**Comment by xhluca** [comment]
@tbridel I am not the maintainer anymore. I would recommend asking the Dash core maintainers instead.

**Comment by tbridel** [comment]
Hi @xhluca, thank you for the quick answer.

Does this mean that dash_vtk has been integrated part of the core of dash ? @nicolaskruchten @jourdain

**Comment by nicolaskruchten** [comment]
It has not been integrated into Dash core, no, but the folks maintaining the core are ultimately maintaining this repo now. I'm no longer involved either :)

**Comment by alexcjohnson** [comment]
We have not had the bandwidth to QA this and prepare a new release for a while now, but I expect we'll be able to in the next couple of months 🤞
