### ISSUE TITLE
No `id` for PointCloudRepresentation

### ISSUE THREAD

**Issue by xhlulu** [plotly/dash-vtk#7]
I'm trying to create a demo where I could dynamically update pointcloudrepresentation using a dash callback. However, I noticed that there's no `id` prop in the `propTypes` of the component; is that intended?

See: https://github.com/plotly/dash-vtk/blob/master/src/lib/components/PointCloudRepresentation.react.js

**Comment by jourdain** [comment]
Probably not

**Comment by jourdain** [comment]
BTW, I don't know if you've noticed but I created such demo (without dynamic update)

**Comment by xhlulu** [comment]
Oh I just noticed! In this case there's no need for me to wrap the `PointCloudRepresentation.react.js` example in Dash. Is there some other examples from the [react-vtk-js/usage](https://github.com/Kitware/react-vtk-js/tree/master/usage) that is not covered by `pyvista`? If so I can wrap them so you can focus on the important stuff

**Comment by jourdain** [comment]
The volume ones won't be covered by pyvista

**Comment by jourdain** [comment]
Should be fixed now

**Comment by jlevy44** [comment]
I am still getting this issue #19
