### ISSUE TITLE
Component only updated by dash callbacks when we click them

### ISSUE THREAD

**Issue by xhlulu** [plotly/dash-vtk#8]
In [demo page](https://kitware.github.io/react-vtk-js/)'s `SourceViewer` demo, we can see that the component is updated every time the slider is dragged:

![react-vtk](https://user-images.githubusercontent.com/21180505/106035480-2cf2a500-60a2-11eb-9f92-53fe113e40d8.gif)

However, the [same demo in Dash](https://github.com/plotly/dash-vtk/tree/master/demos/usage-algorithm) doesn't automatically update the component when the callback is fired by the slider; instead, you have to click on the canvas:

![dash-vtk](https://user-images.githubusercontent.com/21180505/106035892-a094b200-60a2-11eb-995e-7e365e6fe6c4.gif)

Any idea why this might happen?

**Comment by jourdain** [comment]
Yes we need to trigger a render. I've already done the change earlier this morning on the react library. But I will need the update code to change another state on the view.

**Comment by xhlulu** [comment]
Sure! Which update code would it be?

**Comment by jourdain** [comment]
I was retrying to do that,

```


@app.callback(
    Output("vtk-view", "triggerRender"),
    [],
)
def render():
    render_count += 1
    return render_count


@app.callback(
    Output("vtk-algorithm", "state"),
    [Input("slider-resolution", "value"), Input("capping-checklist", "value")],
)
def update_cone(slider_val, checked_values):
    render()
    return {"resolution": slider_val, "capping": "capping" in checked_values}

```

**Comment by xhlulu** [comment]
```
def render():
    render_count += 1
    return render_count


@app.callback(
    [Output("vtk-algorithm", "state"), Output("vtk-view", "triggerRender")],
    [Input("slider-resolution", "value"), Input("capping-checklist", "value")],
)
def update_cone(slider_val, checked_values):
    render()
    return [ {"resolution": slider_val, "capping": "capping" in checked_values}, update]
```

**Comment by xhlulu** [comment]
```
@app.callback(
  Output(...),
  [Input('my-slider'...)],
  [State('graph', 'data')]
)
def update_cone(slider_value, my_data):
  ...
  return ...
```

If graph is updated, the callback will be triggered. but if slider is updated, callback will be triggered.

**Comment by xhlulu** [comment]
@jourdain Just sharing in case you are not aware: I tried running `usage-pyvista-terrain-following-mesh` and the `triggerRender` doesn't seem to work.

**Comment by jourdain** [comment]
need to re-run `npm i`

**Comment by xhlulu** [comment]
Ok it works. thanks!
